/* svg2am — SVG path -> Alight Motion XML. Format diverifikasi dari ekspor AM 5.0.273.
   Fakta terverifikasi: posisi absolut = <location> + koordinat path; urutan XML = bawah ke atas;
   path hanya M / L / C (koma antar titik); path tertutup diakhiri "L" ke titik awal. */
(function (root) {
  'use strict';
  const fmt = n => { const s = String(Math.round(n * 1e6) / 1e6); return s.includes('.') ? s : s + '.0'; };
  const fix6 = n => { const [a, b = ''] = String(Math.round(n * 1e6) / 1e6).split('.'); return a + '.' + (b + '000000').slice(0, 6); };
  const ARGS = { M: 2, L: 2, H: 1, V: 1, C: 6, S: 4, Q: 4, T: 2, Z: 0, A: 7 };

  function parsePath(d) {
    const tk = String(d).match(/[A-Za-z]|[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?/g) || [];
    const subs = []; let cur = null, i = 0, cmd = '', cx = 0, cy = 0, sx = 0, sy = 0, lc = null, lq = null;
    const num = () => { const v = parseFloat(tk[i++]); if (!isFinite(v)) throw new Error('Path rusak: angka tidak valid'); return v; };
    const line = (x, y) => { cur.segs.push({ t: 'L', p: [x, y] }); cx = x; cy = y; };
    const cubic = (a, b, c, e, x, y) => { cur.segs.push({ t: 'C', p: [a, b, c, e, x, y] }); cx = x; cy = y; };
    while (i < tk.length) {
      if (/[A-Za-z]/.test(tk[i])) cmd = tk[i++];
      const up = cmd.toUpperCase(), rel = cmd !== up;
      if (!(up in ARGS)) throw new Error('Perintah path tidak dikenal: ' + cmd);
      if (up === 'A') throw new Error('Arc (A) belum didukung — ubah ke kurva dulu');
      if (up === 'Z') { if (cur) { cur.closed = true; cx = sx; cy = sy; } lc = lq = null; continue; }
      const ox = rel ? cx : 0, oy = rel ? cy : 0, pc = lc, pq = lq; lc = lq = null;
      if (up === 'M') { const x = num() + ox, y = num() + oy; cur = { start: [x, y], segs: [], closed: false }; subs.push(cur); cx = sx = x; cy = sy = y; cmd = rel ? 'l' : 'L'; continue; }
      if (!cur) throw new Error('Path harus diawali M');
      if (up === 'L') line(num() + ox, num() + oy);
      else if (up === 'H') line(num() + ox, cy);
      else if (up === 'V') line(cx, num() + oy);
      else if (up === 'C') { const a = num() + ox, b = num() + oy, c = num() + ox, e = num() + oy, x = num() + ox, y = num() + oy; cubic(a, b, c, e, x, y); lc = [c, e]; }
      else if (up === 'S') { const c = num() + ox, e = num() + oy, x = num() + ox, y = num() + oy; const r = pc ? [2 * cx - pc[0], 2 * cy - pc[1]] : [cx, cy]; cubic(r[0], r[1], c, e, x, y); lc = [c, e]; }
      else {
        let qx, qy; if (up === 'Q') { qx = num() + ox; qy = num() + oy; } else { const r = pq ? [2 * cx - pq[0], 2 * cy - pq[1]] : [cx, cy]; qx = r[0]; qy = r[1]; }
        const x = num() + ox, y = num() + oy, k = 2 / 3;
        cubic(cx + k * (qx - cx), cy + k * (qy - cy), x + k * (qx - x), y + k * (qy - y), x, y); lq = [qx, qy];
      }
    }
    return subs;
  }

  function toAmPath(d, o) {
    o = o || {}; const s = o.scale == null ? 1 : o.scale, ox = o.offX || 0, oy = o.offY || 0;
    const P = (x, y) => fmt(x * s - ox) + ' ' + fmt(y * s - oy);
    return parsePath(d).map(sp => {
      let out = 'M ' + P(sp.start[0], sp.start[1]);
      sp.segs.forEach(g => {
        const p = g.p;
        out += g.t === 'L' ? 'L ' + P(p[0], p[1]) : 'C ' + P(p[0], p[1]) + ', ' + P(p[2], p[3]) + ', ' + P(p[4], p[5]);
      });
      if (sp.closed) out += 'L ' + P(sp.start[0], sp.start[1]);
      return out;
    }).join('');
  }

  function toArgb(fill, opacity) {
    let r = 0, g = 0, b = 0, m;
    fill = String(fill || '#000').trim();
    if ((m = fill.match(/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i))) { r = +m[1]; g = +m[2]; b = +m[3]; }
    else if ((m = fill.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i))) { let h = m[1]; if (h.length === 3) h = h.replace(/./g, '$&$&'); r = parseInt(h.slice(0, 2), 16); g = parseInt(h.slice(2, 4), 16); b = parseInt(h.slice(4), 16); }
    const a = Math.round(255 * (opacity == null || isNaN(opacity) ? 1 : Math.max(0, Math.min(1, opacity))));
    return '#' + [a, r, g, b].map(v => v.toString(16).padStart(2, '0')).join('');
  }
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

  /* o: {title,width,height,fps,totalTime,bg,scale,shapes:[{label,fill,opacity,d}]} — shapes bawah -> atas */
  function buildScene(o) {
    const W = o.width, H = o.height, T = o.totalTime || 3000, loc = fix6(W / 2) + ',' + fix6(H / 2) + ',0.000000';
    const L = ["<?xml version='1.0' encoding='UTF-8' ?><!--\nCreated by Alight Motion (http://alightmotion.com)\nGenerated by Auto Trace\n5.0.273.1028425 (1028425)\n-->"];
    L.push('<scene title="' + esc(o.title || 'Auto Trace') + '" width="' + W + '" height="' + H + '" exportWidth="' + W + '" exportHeight="' + H + '" precompose="dynamicResolution" bgcolor="' + (o.bg || '#ffffffff') + '" totalTime="' + T + '" fps="' + (o.fps || 30) + '" modifiedTime="' + Date.now() + '" amver="1028425" ffver="106" am="com.alightcreative.motion/5.0.273.1028425" amplatform="android" retime="freeze" retimeAdaptFPS="false">');
    o.shapes.forEach((sh, i) => {
      L.push('  <shape id="' + (2000000000 + i + 1) + '" label="' + esc(sh.label || 'Trace ' + (i + 1)) + '" startTime="0" endTime="' + T + '" fillType="color" mediaFillMode="fill">',
        '    <transform>', '      <location value="' + loc + '" />', '    </transform>',
        '    <fillColor value="' + toArgb(sh.fill, sh.opacity) + '" />',
        '    <path d="' + toAmPath(sh.d, { scale: o.scale, offX: W / 2, offY: H / 2 }) + '" />', '  </shape>');
    });
    L.push('</scene>');
    return L.join('\r\n');
  }

  const api = { parsePath, toAmPath, toArgb, buildScene };
  if (typeof module === 'object' && module.exports) module.exports = api; else root.Svg2Am = api;
})(typeof window !== 'undefined' ? window : this);
